### ISSUE TITLE
empty result tables

### ISSUE THREAD

**Issue by astridboehne** [gengit/PosiGene#1]
Hi 
I installed PosiGen on a Unix cluster and the test run worked smoothly.
Now I wanted to run it with two fish non homologen species and Danio rerio as the only fish homologen and outgroup.
this is the command I used:
perl /scicore/home/salzburg/boehne/applications/PosiGene-master/PosiGene.pl \
-nhsbr=Eretmodus_Female:/scicore/home/salzburg/eltaher/KissSplice/ecyanostictus_F_M/TransDec_F/Trinity.fasta.transdecoder.cds,$HOME/applications/PosiGene-master/data/Oreochromis_niloticus.gbk,$HOME/applications/PosiGene-master/data/Danio_rerio.gbk \
-ts=Eretmodus_Female \
-as=Oreochromis_niloticus \
-rs=$HOME/applications/PosiGene-master/data/Oreochromis_niloticus.gbk \
-o=$HOME/Ambizione/KaKs_transcriptomes/PosiGen/ecyanostictus_F/Orenil_anchor \
-tn=16 \
-t=$HOME/Ambizione/KaKs_transcriptomes/PosiGen/ecyanostictus_F/ErecyaF.nwk

I did run it without a tree first but got the error not enough information to build tree.
So I added the species tree and everything seems to run fine, all files are created but the results table contain only the headers and nothing else
I attach you all the log files and STDOUT, STDERR was empty
Any help would be great
[logs.zip](https://github.com/gengit/PosiGene/files/902408/logs.zip)
[PosiGenEreF.o28336384.txt](https://github.com/gengit/PosiGene/files/902411/PosiGenEreF.o28336384.txt)
[progress.txt](https://github.com/gengit/PosiGene/files/902410/progress.txt)

**Comment by tianrenmao** [comment]
I am a user of PosiGene. 
I suggest you simplify all your species name. For example, change Oreochromis_niloticus to "a". Also -rs had better be fed with fasta. All the fasta files had better end with ".fasta". You don't really need to provide a tree file. 
Tell me if it works.

**Comment by astridboehne** [comment]
Hi
the solution was to shorten the sequence names in the transdecoder output file.
Thanks Arne for helping!
