### ISSUE TITLE
Output files lack dN/dS statistic

### ISSUE THREAD

**Issue by rprops** [gengit/PosiGene#2]
Hi,

I've been enjoying PosiGene! I'm especially pleased that the software contains all necessary dependencies!

However, in the paper it states that the output files should contain dN/dS ratios of each gene, but I could not find these in the several output files. I would however not only like to know which genes are potentially under positive selection, but also the extent by which they are (dN/dS ratio). As far as I understand, solely using the number of positions under positive selection is only a proxy for this due to gene length/dS variations. 

Reference in paper:
_"The output consists of a table showing all genes (including those that are not significant) ranked by their probability to be under positive selection and includes information about positively selected sites, dN/dS ratios as well as links to alignment visualizations."_

Example tabular output (results_short.tsv file) from PosiGene:

```
Gene	Transcript	FDR	P-Value	Number of species included	Number of Sites under positive Selection	Jalview protein alignment	Protein Alignment (interleaved)
2727791807	2727791807	8.828326e-12	9.659e-15	8	80	"/posigene_analysis/individual_results/2727791807/MAG1/2727791807_codeml/prank/prank.best.fas.translation.view"	"LibGD or perl module GD not installed"	
2727791696	2727791696	3.342955e-09	7.315e-12	9	50	"/posigene_analysis/individual_results/2727791696/MAG1/2727791696_codeml/prank/prank.best.fas.translation.view"	"LibGD or perl module GD not installed"
...
```

Thank you for your assistance,

Ruben

**Comment by asahm** [comment]
This information can be found in the main result table (results.tsv) in the 19th column named "HA foreground omega".

Best regards
Arne
